### ISSUE TITLE
Json hatası

### ISSUE THREAD

**Issue by mGungorr** [thodex-exchange/thodex-vbnet-api#1]
Merhabalar, görselde görünen hatayı alıyorum ? Nasıl çözebilirim ?

![image](https://user-images.githubusercontent.com/69353577/96276690-040b4000-0fdc-11eb-9d50-eaca81cc7892.png)

**Comment by letreset** [comment]
https://github.com/thodex-exchange/thodex-vbnet-api/commit/66928da6d36a8eeed721bfb25dbfac7c9f41c5c9
