### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: 'Error reading JObject from JsonReader. Path '', line 0, position 0.'

### ISSUE THREAD

**Issue by hakkietem350** [thodex-exchange/thodex-vbnet-api#2]
ThodexAPI.vb - Line 193

**Comment by letreset** [comment]
You need to get api key from thodex user panel and api secret and add into ThodexAPI.vb, line 8 and 9

**Comment by letreset** [comment]
#1

**Comment by hakkietem350** [comment]
I added my normal key to one and secret one to other but it didnt work
