### ISSUE TITLE
Newtonsoft.Json.JsonReaderException: 'Error reading JObject from JsonReader. Path '', line 0, position 0.' 

### ISSUE THREAD

**Issue by hakkietem350** [thodex-exchange/thodex-vbnet-api#3]
Adding api and secret key doesnt change anything it still gives same error as i said

**Comment by letreset** [comment]
This error caused by a mismatch of the security binding between the client and the server. Fixed with this commit
https://github.com/thodex-exchange/thodex-vbnet-api/commit/66928da6d36a8eeed721bfb25dbfac7c9f41c5c9
