### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by ermanertas** [thodex-exchange/thodex-vbnet-api#4]
i keep getting error 610 invalid authorization. 

![resim](https://user-images.githubusercontent.com/25755316/101292453-91bb1d00-3820-11eb-8772-24cccf3c00a4.png)

it seems i produce wrong auth token, 

to produce token, i got params included tonce and apikey and prepare the following text, than hashing it with sha256 and use it at headers. 

![resim](https://user-images.githubusercontent.com/25755316/101292574-6422a380-3821-11eb-8581-9c33358eb154.png)

![resim](https://user-images.githubusercontent.com/25755316/101292611-a9df6c00-3821-11eb-83a1-77815590dd5e.png)

what could be the reason? could you guide me? i use my custom python code for rest api. I couldn't find any other place to ask.

**Comment by letreset** [comment]
Your hash string was wrong. It starts with 'asset=USDT', it must be like 'apikey=XXX&tonce=1234&secret=YYY'
If you would like to share your thodex python lib we will publish it 👍

**Comment by ermanertas** [comment]
thanks alot, it works when i take out the asset for balance check. However, what about when i want to add some parameters? 
For example, trying to place a limit order like below, do i need to add paramaters to hash string or should it only consist of apikey, tonce and secret?

![resim](https://user-images.githubusercontent.com/25755316/101411577-44a77b80-38f2-11eb-9c5a-d179cefac71b.png)

by the way, i really want to share lib once i got it running and tidy it up a little bit.

**Comment by letreset** [comment]
Hash string should only contains apikey,tonce,secret (as written order) for all private requests. You can check request parameters from postman sample https://github.com/thodex-exchange/thodex-postman-api
