### ISSUE TITLE
matching order id's

### ISSUE THREAD

**Issue by ermanertas** [thodex-exchange/thodex-vbnet-api#5]
Order id's we got from open orders - buy-sell api end and order history api end doesn't match, how can we match orders?

limit sell:
{'error': None, 'result': {'id': 337977706, 'market': 'BTCUSDT', 'source': 'api', 'type': 1, 'side': 1, 'ctime': 1608388554.917667, 'mtime': 1608388554.917667, 'price': '23210', 'amount': '0.0003', 'taker_fee': '0', 'maker_fee': '0', 'left': '0.0003', 'deal_stock': '0', 'deal_money': '0', 'deal_fee': '0'}}

order history:
{'time': 1608388812.369806, 'user': 248478, 'id': 9259803, 'side': 1, 'role': 1, 'price': '23210', 'amount': '0.0003', 'deal': '6.963', 'fee': '0', 'deal_order_id': 337987553, 'market': 'BTCUSDT'},

**Comment by ersisk** [comment]
You are asking for finished orders; yet our "order history" call returns deal history actually. Please use "order-finished" call that we added recently.

**Comment by ermanertas** [comment]
Can we use it from;
v1/market/order-finished 

Parameters will be same as order history i think?

**Comment by ersisk** [comment]
The parameters will be the same as  open orders. I will share the document link when endpoint is published.

**Comment by ersisk** [comment]
Endpoints is live. Here you go:

https://api.thodex.com/#api-Market-getFinishedOrder
https://api.thodex.com/#api-Market-getFinishedOrderInfo
https://api.thodex.com/#api-Market-getOpenOrderInfo
